// LibreSolvE.Core/Parsing/AstBuilderVisitor.cs
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using LibreSolvE.Core.Ast;
using System;
using System.Collections.Generic;
using System.Globalization; // For consistent number parsing
using System.Linq;
using Antlr4.Runtime; // For Token information for error reporting

namespace LibreSolvE.Core.Parsing;

/// <summary>
/// Visitor that walks the ANTLR parse tree generated by EesParser
/// and builds an Abstract Syntax Tree (AST) using LibreSolvE.Core.Ast node classes.
/// </summary>
public class AstBuilderVisitor : EesParserBaseVisitor<AstNode>
{
    /// <summary>Stamps a freshly-constructed node with the source line of the
    /// parse-tree context it came from. Every Visit* method that actually
    /// constructs a node (as opposed to delegating via Visit(...)) routes its
    /// return through this, so AstNode.Line is populated uniformly rather
    /// than at some construction sites and not others.</summary>
    private static T WithLine<T>(T node, ParserRuleContext context) where T : AstNode
    {
        node.Line = context.Start.Line;
        return node;
    }

    #region File Level Visitor
    /// <summary>
    /// Visits the root of the parse tree (the entire file).
    /// </summary>
    /// <param name="context">The parse tree context for the file.</param>
    /// <returns>An EesFileNode representing the root of the AST.</returns>
    public override AstNode VisitEesFile([NotNull] EesParser.EesFileContext context)
    {
        var fileNode = new EesFileNode();
        // Iterate through each statement context within the file context
        foreach (var statementContext in context.statement())
        {
            // Visit the specific statement alternative (e.g., AssignmentStatement, EquationStatement)
            var statementNode = Visit(statementContext);
            if (statementNode is StatementNode stmt)
            {
                fileNode.Statements.Add(stmt); // Add the resulting AST node to the file node's list
            }
            else if (statementNode != null)
            {
                // This case shouldn't typically happen if the grammar and visitor are correct,
                // but good for diagnostics if it does.
                Console.Error.WriteLine($"Warning: Visiting statement rule resulted in a non-StatementNode AST node: {statementNode.GetType().Name}");
            }
            // If statementNode is null, ANTLR might have skipped something or there was an issue.
        }
        return fileNode;
    }
    #endregion File Level Visitor

    #region Statement Level Visitors
    // These methods correspond to the # labels on the 'statement' rule alternatives
    // in the grammar. They primarily delegate to the visitor for the specific
    // underlying rule (assignment or equation).

    /// <summary>
    /// Visits the context corresponding to the '# AssignmentStatement' label in the grammar.
    /// Delegates to visit the actual 'assignment' rule context contained within.
    /// </summary>
    public override AstNode VisitAssignmentStatement([NotNull] EesParser.AssignmentStatementContext context)
    {
        // The context holds the result of matching the 'assignment' rule. Visit that specific rule context.
        return Visit(context.assignment());
    }

    /// <summary>
    /// Visits the context corresponding to the '# EquationStatement' label in the grammar.
    /// Delegates to visit the actual 'equation' rule context contained within.
    /// </summary>
    public override AstNode VisitEquationStatement([NotNull] EesParser.EquationStatementContext context)
    {
        // The context holds the result of matching the 'equation' rule. Visit that specific rule context.
        return Visit(context.equation());
    }

    /// <summary>
    /// Visit a directive statement and create a DirectiveNode
    /// </summary>
    public override AstNode VisitDirectiveStatement([NotNull] EesParser.DirectiveStatementContext context)
    {
        string directiveText = context.DIRECTIVE().GetText();
        return WithLine(new DirectiveNode(directiveText), context);
    }

    // VisitPlotStatement removed along with the PlotStatement grammar rule
    // (COMPATIBILITY.md Rule 5) -- PlotCommandNode is now only ever
    // constructed from PlotDirectiveParser's comment-text extraction, in
    // StatementExecutor.Execute, not from the parse tree.
    #endregion Statement Level Visitors

    #region Rule Level Visitors for Equations and Assignments
    // These methods visit the specific grammar rules (equation, assignment alternatives)
    // and construct the corresponding AST nodes using the labeled elements from the grammar.

    /// <summary>
    /// Visits the 'equation' rule context.
    /// Constructs an EquationNode from the left-hand side and right-hand side expressions.
    /// </summary>
    public override AstNode VisitEquation([NotNull] EesParser.EquationContext context)
    {
        // Grammar rule: equation: lhs=expression EQ rhs=expression SEMI? ;
        ExpressionNode lhs = (ExpressionNode)Visit(context.lhs); // Visit the labeled 'lhs' expression
        ExpressionNode rhs = (ExpressionNode)Visit(context.rhs); // Visit the labeled 'rhs' expression
        return WithLine(new EquationNode(lhs, rhs), context);
    }

    /// <summary>
    /// Visits the 'ExplicitAssignment' rule context (using ':=').
    /// In the main program block, this is a syntax error according to EES.
    /// Throws a ParsingException.
    /// </summary>
    public override AstNode VisitExplicitAssignment([NotNull] EesParser.ExplicitAssignmentContext context)
    {
        // Grammar rule: assignment: variable=ID ASSIGN rhs=expression SEMI?   # ExplicitAssignment
        // EES reserves ':=' for assignments within FUNCTIONS and PROCEDURES.
        // In the main program block (which this parser pass handles), this is a syntax error.

        IToken assignToken = context.ASSIGN().Symbol;
        IToken variableToken = context.variable;

        IToken errorReferenceToken = assignToken ?? variableToken ?? context.Start;

        int line = errorReferenceToken.Line;
        int charPositionInLine = errorReferenceToken.Column;
        string varName = context.variable.Text;

        string errorMessage = $"Error at Line {line}:{charPositionInLine} near '{varName} := ...': " +
                              "Syntax error. The colon (from explicit assignment ':=') is reserved. " +
                              "In the main program, use '=' for assignments and equations. " +
                              "':=' is used for assignments within FUNCTIONS and PROCEDURES.";

        throw new ParsingException(errorMessage); // THIS IS THE KEY CHANGE TO REINTRODUCE THE ERROR
    }

    /// <summary>
    /// Visits the 'ImplicitAssignment' rule context (using '=').
    /// Constructs an EquationNode. The StatementExecutor will later categorize
    /// this as an assignment if the RHS evaluates to a constant expression.
    /// </summary>
    public override AstNode VisitImplicitAssignment([NotNull] EesParser.ImplicitAssignmentContext context)
    {
        // Grammar rule: assignment: variable=ID EQ rhs=expression SEMI?       # ImplicitAssignment
        VariableNode lhs = WithLine(new VariableNode(context.variable.Text), context);
        ExpressionNode rhs = (ExpressionNode)Visit(context.rhs);
        return WithLine(new EquationNode(lhs, rhs), context);
    }
    #endregion Rule Level Visitors for Equations and Assignments

    #region Expression Visitors
    // These methods visit the different expression rule alternatives (# labels)
    // and construct the corresponding AST expression nodes.

    /// <summary>
    /// Visits a unary minus expression.
    /// </summary>
    public override AstNode VisitUnaryMinusExpr([NotNull] EesParser.UnaryMinusExprContext context)
    {
        ExpressionNode operand = (ExpressionNode)Visit(context.expression());

        // Create a binary operation with 0 - operand
        return WithLine(new BinaryOperationNode(
            WithLine(new NumberNode(0.0), context),
            BinaryOperator.Subtract,
            operand), context);
    }

    /// <summary>
    /// Visits a power expression.
    /// </summary>
    public override AstNode VisitPowExpr([NotNull] EesParser.PowExprContext context)
    {
        ExpressionNode left = (ExpressionNode)Visit(context.left);
        ExpressionNode right = (ExpressionNode)Visit(context.right);
        return WithLine(new BinaryOperationNode(left, BinaryOperator.Power, right), context);
    }

    /// <summary>
    /// Visits a multiplication or division expression.
    /// </summary>
    public override AstNode VisitMulDivExpr([NotNull] EesParser.MulDivExprContext context)
    {
        ExpressionNode left = (ExpressionNode)Visit(context.left);   // Visit labeled left operand
        ExpressionNode right = (ExpressionNode)Visit(context.right); // Visit labeled right operand
        // Determine operator type based on the token type from the labeled 'op'
        BinaryOperator op = context.op.Type == EesLexer.MUL ? BinaryOperator.Multiply : BinaryOperator.Divide;
        return WithLine(new BinaryOperationNode(left, op, right), context);
    }

    /// <summary>
    /// Visits an addition or subtraction expression.
    /// </summary>
    public override AstNode VisitAddSubExpr([NotNull] EesParser.AddSubExprContext context)
    {
        ExpressionNode left = (ExpressionNode)Visit(context.left);   // Visit labeled left operand
        ExpressionNode right = (ExpressionNode)Visit(context.right); // Visit labeled right operand
        // Determine operator type based on the token type from the labeled 'op'
        BinaryOperator op = context.op.Type == EesLexer.PLUS ? BinaryOperator.Add : BinaryOperator.Subtract;
        return WithLine(new BinaryOperationNode(left, op, right), context);
    }

    /// <summary>
    /// Visits a parenthesized expression. Returns the AST node for the inner expression.
    /// This is part of the 'atom' rule in the grammar, but acts as a precedence controller for expressions.
    /// </summary>
    public override AstNode VisitParenExpr([NotNull] EesParser.ParenExprContext context)
    {
        // Grammar rule: atom: LPAREN expression RPAREN # ParenExpr
        // Simply visit the nested expression context
        return Visit(context.expression());
    }
    #endregion Expression Visitors

    #region Atom Visitors
    // These methods visit the specific atom rule alternatives (# labels)

    /// <summary>
    /// Visits a NUMBER literal token and creates a NumberNode.
    /// </summary>
    public override AstNode VisitNumberAtom([NotNull] EesParser.NumberAtomContext context)
    {
        string text = context.NUMBER().GetText();
        // Use InvariantCulture for reliable decimal parsing regardless of system locale
        if (double.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture, out double value))
        {
            return WithLine(new NumberNode(value), context);
        }
        // It's generally better to throw a more specific exception or handle errors gracefully.
        throw new FormatException($"Could not parse number: {text}");
    }

    /// <summary>
    /// Visits an ID token and creates a VariableNode.
    /// </summary>
    public override AstNode VisitVariableAtom([NotNull] EesParser.VariableAtomContext context)
    {
        return WithLine(new VariableNode(context.ID().GetText()), context);
    }

    /// <summary>
    /// Visits a STRING_LITERAL token and creates a StringLiteralNode.
    /// </summary>
    public override AstNode VisitStringAtom([NotNull] EesParser.StringAtomContext context)
    {
        // Get the full text, including quotes, and pass to the node constructor for unescaping
        string literalWithQuotes = context.STRING_LITERAL().GetText();
        return WithLine(new StringLiteralNode(literalWithQuotes), context);
    }

    /// <summary>
    /// Visits a function call atom and delegates to the function call visitor.
    /// </summary>
    public override AstNode VisitFuncCallAtom([NotNull] EesParser.FuncCallAtomContext context)
    {
        return Visit(context.functionCall());
    }
    #endregion Atom Visitors

    #region Function Call Visitor
    /// <summary>
    /// Visits a function call and creates a FunctionCallNode.
    /// </summary>
    public override AstNode VisitFunctionCall([NotNull] EesParser.FunctionCallContext context)
    {
        string functionName = context.fname.Text; // fname is the ID token
        var arguments = new List<ExpressionNode>();

        // Process arguments if any
        if (context.exprList() != null)
        {
            foreach (var exprContext in context.exprList().expression())
            {
                var argNode = Visit(exprContext);
                if (argNode is ExpressionNode expr)
                {
                    arguments.Add(expr);
                }
                else
                {
                    Console.Error.WriteLine($"Warning: Function argument produced non-expression node: {argNode?.GetType().Name}");
                }
            }
        }

        return WithLine(new FunctionCallNode(functionName, arguments), context);
    }
    #endregion Function Call Visitor

    #region Default Aggregation (Optional but good practice)
    /// <summary>
    /// Controls how results from visiting multiple children are combined.
    /// The default ANTLR behavior often returns the result of the last child visited.
    /// For building a specific AST node in overridden methods, this default is usually fine.
    /// If a rule has multiple children and you want to aggregate them (e.g., into a list),
    /// you'd override the specific VisitMyRule and handle aggregation there.
    /// This method is a fallback.
    /// </summary>
    protected override AstNode AggregateResult(AstNode aggregate, AstNode nextResult)
    {
        // If nextResult is null, stick with the current aggregate.
        // This is often the desired behavior when visiting optional parts of rules.
        return nextResult ?? aggregate;
    }
    #endregion Default Aggregation
}
